import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  console.log("API KEY STRIPE", process.env.NEXT_PUBLIC_STRIPE_API_KEY);
  return (
    <>
      <Head>
        <title>Space Jelly Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.center}>
          <h1>Space Jelly Shop</h1>
          <h2>The best Jellyfish swag on the web</h2>
        </div>

        <ul className={styles.grid}>
          <li className={styles.card}>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <img src="/images/spacejelly-tshirt.jpg" atl="Space Jelly Tshirt"/>
              <h3 className={inter.className}>
                Space Jelly Tshirt	
              </h3>
              <p className={inter.className}>
                Bring Cosmo the space Jellyfish to your wardrobe with this high quality tshirt.
              </p>
            </a>
            <p>
              <button className="button">Buy Now!</button>
            </p>
          </li>

          <li className={styles.card}>
            <a
              href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <img src="/images/spacejelly-stickers.jpg" atl="Space Jelly Stickers"/>
              <h3 className={inter.className}>
                Space Jelly Stickers	
              </h3>
              <p className={inter.className}>
                Add some flare to your laptop with a sticker of Cosmo the Space Jellyfish.
              </p>
            </a>
          </li>

          <li className={styles.card}>
            <a
              href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <img src="/images/spacejelly-combo.jpg" atl="Space Jelly Combo"/>
              <h3 className={inter.className}>
                Space Jelly Combo	
              </h3>
              <p className={inter.className}>
                Show your love for Cosmo with a tshirt and sticker combo pack!
              </p>
            </a>
          </li>
        </ul>
      </main>
    </>
  )
}
