import Head from 'next/head';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import { FaShoppingCart } from 'react-icons/fa';
import styles from '@/styles/Home.module.css';
import products from "../../products.json";
import { useCart } from '../../hooks/use-cart.js';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {totalItems, subtotal, addToCart, checkout} = useCart();

  return (
    <div className={styles.container}>
      <Head>
        <title>Space Jelly Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
 
        <div>
          <h2 className={inter.className}>The best Jellyfish swag on the web</h2>
        </div>

        <div className={styles.center}>
          <p>
            <strong>Items:</strong> {totalItems}
          </p>
          <p>
            <strong>Total Cost:</strong> {subtotal} €
          </p>
          <br />
          <button className={`${styles.button} ${styles.cartButton}`} onClick={checkout}>
            <FaShoppingCart />
             Check Out
          </button>
        </div>

        <ul className={styles.grid}>
          {products.map( product => {
            const {id, title, image, description, price} = product
            return (
            <li key={id} className={styles.card}>
              <Link href={`/products/${id}`}>
                  <img src={image} atl={title}/>
                  <h3 className={inter.className}>
                    {title}	
                  </h3>
                  <p className={styles.price} >{price} €</p>
                  <p className={inter.className}>
                    {description}
                  </p>
              </Link>
              <p>
                <button className={styles.button} onClick={() => { 
                  addToCart({id})
                }}>
                    Add to Cart
                </button>
              </p>
            </li>)

          })}
        </ul>
      </main>
    </div>
  )
}
