import { useState } from 'react';
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { initiateCheckout } from '../../lib/payments'
import products from "../../products.json";

const inter = Inter({ subsets: ['latin'] })

const defaultCart = {
  products: {}
}

export default function Home() {

  const [cart, updateCart] = useState(defaultCart);
  //console.log('cart', cart);

  const cartItems = Object.keys(cart.products).map( key => {
    const product = products.find( ({id}) => `${id}` === `${key}` )
    return {
      ...cart.products[key],
      pricePerItem: product.price
    }
  })

  const subtotal = cartItems.reduce( (accumulator, {pricePerItem, quantity} ) => {
    const totalPrice = accumulator + (pricePerItem * quantity)
    return totalPrice
  }, 0)

  console.log('cartItems', cartItems);
  console.log('subtotal', subtotal);

  const addToCart = ({id} = {}) => {
    updateCart(prev => {
      let cartState = {...prev};

      if(cartState.products[id]) {
        cartState.products[id].quantity = cartState.products[id].quantity + 1;
      } else {
        cartState.products[id] = {
          id,
          quantity: 1
        }
      }
      return cartState
    })
  }

  return (
    <>
      <Head>
        <title>Space Jelly Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
 
        <div className={styles.center}>
          <h1>Space Jelly Shop</h1>
          <h2>The best Jellyfish swag on the web</h2>
        </div>

        <div className={styles.center}>
          <p>
            <strong>Items:</strong> 2
            <br />
            <strong>Total Cost:</strong> 20€
            <br />
            <button className={styles.button.checkout}>Check Out</button>
          </p>
        </div>

        <ul className={styles.grid}>
          {products.map( product => {
            const {id, title, image, description, price} = product
            return (
            <li key={id} className={styles.card}>
              <a
                href="#"
                target="_blank"
                rel="noopener noreferrer"
              >
                <img src={image} atl={title}/>
                <h3 className={inter.className}>
                  {title}	
                </h3>
                <p className={styles.price} >{price} €</p>
                <p className={inter.className}>
                  {description}
                </p>
              </a>
              <p>
                <button className={styles.button} onClick={() => { 
                  // initiateCheckout({
                  //   lineItems: [{
                  //     price: id, // Replace with the ID of your price
                  //     quantity: 1,
                  //   }]
                  // }) 
                  addToCart({id})
                }}>
                    Add to Cart
                </button>
              </p>
            </li>)

          })}
        </ul>
      </main>
    </>
  )
}
